export const GAME_CANVAS_WIDTH = 1248;
export const GAME_CANVAS_HEIGHT = 768;

export const MAIN_SCENE_PRIMARY_WIDTH = 1024;
export const MAIN_SCENE_NOTES_PANEL_WIDTH =
  GAME_CANVAS_WIDTH - MAIN_SCENE_PRIMARY_WIDTH;
